# Generated by Django 5.1.7 on 2025-03-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_userprofileinfo_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user_type',
        ),
    ]
