# Generated by Django 5.1.7 on 2025-03-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_userprofileinfo_needs_userprofileinfo_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='assigned_patients',
            field=models.ManyToManyField(blank=True, related_name='assigned_volunteers', to='basic_app.userprofileinfo'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='municipality',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='region',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='skills',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('volunteer', 'Volunteer')], default='patient', max_length=20),
        ),
    ]
