# Generated by Django 5.1.7 on 2025-03-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_remove_userprofileinfo_needs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
    ]
